server:
  port: 9001
spring:
  application:
    name: turbine
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://127.0.0.1:8765/eureka/ #http://127.0.0.1:${server.port}/eureka/
  instance:
    prefer-ip-address: true
turbine:
  app-config: serverConsumer,serverConsumer2
  cluster-name-expression: "'default'"