spring:
  application:
    name: zuul
server:
  port: 8000
zuul:
  routes:
    serverConsumer:
      path: /consumer/**
      stripPrefix: true
      sensitiveHeaders:
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8765/eureka/ #http://127.0.0.1:${server.port}/eureka/
  instance:
    prefer-ip-address: true
