server:
  port: 7001

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://127.0.0.1:8765/eureka/ #http://127.0.0.1:${server.port}/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: serverProvide